services:
  backend:
    container_name: sc_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./publuc:/app/public
    networks:
      - proxynet
networks:
  proxynet:
    external: true
